---
name: Tkx-FindBar
version: 0.07
author:
  - 'Michael J. Carman <mjcarman@cpan.org>'
abstract: Perl Tkx extension for an incremental search toolbar
license: perl
resources:
  license: ~
requires:
  Carp: 0
  Tkx: 0
build_requires:
  Test::More: 0
provides:
  Tkx::FindBar:
    file: lib/Tkx/FindBar.pm
    version: 0.07
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
